
import * as XLSX from 'xlsx';
import { Document, Packer, Paragraph, TextRun, HeadingLevel, Table, TableRow, TableCell, WidthType } from 'docx';
import pptxgen from "pptxgenjs";

export const exportToExcel = (headers: string[], rows: any[][], filename: string) => {
    const worksheet = XLSX.utils.aoa_to_sheet([headers, ...rows]);
    const workbook = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(workbook, worksheet, "Data");
    XLSX.writeFile(workbook, `${filename}.xlsx`);
};

export const exportToWord = async (headers: string[], rows: any[][], filename: string) => {
    const doc = new Document({
        sections: [{
            properties: {},
            children: [
                new Paragraph({
                    text: filename.replace(/_/g, ' '),
                    heading: HeadingLevel.HEADING_1,
                    spacing: { after: 400 },
                }),
                new Paragraph({
                    text: `Generated by GridFlow AI - ${new Date().toLocaleDateString()}`,
                    spacing: { after: 200 },
                }),
                new Table({
                    width: {
                        size: 100,
                        type: WidthType.PERCENTAGE,
                    },
                    rows: [
                        new TableRow({
                            children: headers.map(header => new TableCell({
                                children: [new Paragraph({ text: header, style: 'Bold' })],
                                shading: { fill: "f3f4f6" }
                            })),
                        }),
                        ...rows.map(row => new TableRow({
                            children: row.map(cell => new TableCell({
                                children: [new Paragraph({ text: String(cell) })],
                            })),
                        })),
                    ],
                }),
            ],
        }],
    });

    const blob = await Packer.toBlob(doc);
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${filename}.docx`;
    a.click();
    window.URL.revokeObjectURL(url);
};

export const exportToPPT = async (headers: string[], rows: any[][], filename: string) => {
    const pres = new pptxgen();

    // Title Slide
    let slide = pres.addSlide();
    slide.addText("GridFlow AI Extraction Report", { x: 1, y: 1, w: 8, h: 1, fontSize: 36, bold: true, align: 'center', color: '333333' });
    slide.addText(filename.replace(/_/g, ' '), { x: 1, y: 2, w: 8, h: 1, fontSize: 24, align: 'center', color: '666666' });

    // Data Slides
    if (rows.length > 0) {
        // Option A: Split rows into multiple slides if many
        // For now, let's create a slide per 5 rows to keep it readable
        const chunkSize = 8;
        for (let i = 0; i < rows.length; i += chunkSize) {
            const chunk = rows.slice(i, i + chunkSize);
            let dataSlide = pres.addSlide();
            dataSlide.addText(`Data Table (Part ${Math.floor(i / chunkSize) + 1})`, { x: 0.5, y: 0.5, fontSize: 18, bold: true });

            const tableData = [
                headers,
                ...chunk
            ];

            dataSlide.addTable(tableData, { x: 0.5, y: 1.2, w: 9, fontSize: 10, border: { type: 'solid', color: 'E2E8F0' } });
        }
    }

    pres.writeFile({ fileName: `${filename}.pptx` });
};

export const exportToCSV = (headers: string[], rows: any[][], filename: string) => {
    const worksheet = XLSX.utils.aoa_to_sheet([headers, ...rows]);
    const csvContent = XLSX.utils.sheet_to_csv(worksheet);
    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${filename}.csv`;
    a.click();
    window.URL.revokeObjectURL(url);
};
